name: Deploy IAM website

on:
  push:
    branches:
      - v**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout target repo code
        uses: actions/checkout@v2
        with:
          repository: indigo-iam/indigo-iam.github.io
          path: target
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Checkout source repo code
        uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: build & deploy website
        run: |
          ls -al && pwd
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          pushd source && npm ci && HUGO_OPTS="-F" TARGET_DIR="${GITHUB_WORKSPACE}/target" ./deploy.sh && popd
          pushd target && git add . && git commit -m "${{ github.event.head_commit.message }}" && git push
