name: Deploy IAM website

on:
  push:
    branches:
      - v1.7.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.86.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout target repo code
        uses: actions/checkout@v2
        with:
          repository: indigo-iam/indigo-iam.github.io
          path: target
          ref: main

      - name: Checkout source repo code
        uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - run: |
          ls -al && pwd
          pushd source && npm ci && TARGET_DIR="${GITHUB_WORKSPACE}/target" ./deploy.sh && popd
          pushd target && git status

